### ISSUE TITLE
Create Activity Model and Schema

### ISSUE THREAD

**Issue by kaesae** [Lark-GA/my-health-api#4]

**Comment by rneimeyer** [comment]
- Date
- Type (dropdown)
    - Walk
    - Run
    - Yoga
    - Core
    - Arms
    - Full body strength
    - Legs
    - Back
    - Swim
    - Dance
    - Bike
    - Sports
    - Hiking
    - Rowing
    - Pilates 
    - HIIT
- Length (in minutes)
    - Number input
- Intensity (scale 1-10)
